services:
    webapp:
        image: webapp
        build:
            dockerfile: ./webapp/Dockerfile
            args:
                - target=dev
        environment:
            APP_ENV: dev
            PORT: 80
            WEBAPP_DB_HOST: webapp-db
            WEBAPP_DB_PORT: 3306
            WEBAPP_DB_USER: root
            WEBAPP_DB_PASSWORD: root
            WEBAPP_DB_DATABASE: webapp
        ports:
            - 80:80
        volumes:
            - ./webapp:/app:delegated
        working_dir: /app
        links:
            - webapp-db

    # auroraのバージョンと合わせる
    webapp-db:
        image: mysql:8.0.32
        ports:
            - 13306:3306
        environment:
            - MYSQL_DATABASE=webapp
            - MYSQL_ROOT_PASSWORD=root
